### ISSUE TITLE
Update the package

### ISSUE THREAD

**Issue by GiorgioCerro** [GiorgioCerro/hyparticle-net#35]
It seems Mauricio has been an incredible job! We now have a hyperbolic NN that works and gives interesting results with fake data. This is a perfect starting point. THANK YOU.

The new branch seems very cool and well organised. It would be awesome to create a pull request so that the folder can be a clean package installable by anyone. 

Things to do:

- clean the main
- create a pull request

**Comment by GiorgioCerro** [comment]
src:

-  new model
- data handler
- data_generator (folder)
- old_model

notebooks:

- examples etc..

environment.yaml
readme
setup
gitignore

**Comment by mjadiaz** [comment]
I made the pull request. This pull would be the first version of the package. Now I think we would need to improve the structure, type hinting and documentation. Also, include the original code.
